INSERT INTO shopping_list (item_name, item_price, category, checked, date_added)
VALUES
    ('Fish tricks', 13.10, 'main',              false,  now() - '21 days'::INTERVAL),
    ('Not Dogs', 4.99, 'snack',                 true,   now() - '21 days'::INTERVAL),
    ('Bluffalo Wings', 5.50, 'snack',           false,  now() - '21 days'::INTERVAL),
    ('SubstiTuna Salad', 1.24, 'lunch',         false,  now() - '21 days'::INTERVAL),
    ('Tofurkey', 2.50, 'breakfast',             false,  now() - '21 days'::INTERVAL),
    ('Pretenderloins', 9.99, 'main',            false,  now() - '9 days'::INTERVAL),
    ('Steak-believe', 6.00, 'main',             false,  now() - '9 days'::INTERVAL),
    ('Kale Seitan', 6.67, 'breakfast',          false,  now() - '9 days'::INTERVAL),
    ('NoBull Burger', 2.00, 'snack',            false,  now() - '9 days'::INTERVAL),
    ('Turnip the Beet', 0.20, 'lunch',          true,   now() - '9 days'::INTERVAL),
    ('Mascarphony', 1.80, 'lunch',              true,   now() - '7 days'::INTERVAL),
    ('Burgatory', 1.50, 'main',                 false,  now() - '7 days'::INTERVAL),
    ('Sleight of Ham', 3.10, 'lunch',           false,  now() - '5 days'::INTERVAL),
    ('Antichovies', 1.00, 'breakfast',          false,  now() - '5 days'::INTERVAL),
    ('Lettuce B. Frank', 0.86, 'lunch',         true,   now() - '5 days'::INTERVAL),
    ('Pepperphony', 1.40, 'breakfast',          false,  now() - '5 days'::INTERVAL),
    ('Shamburger', 3.50, 'main',                false,  now() - '4 days'::INTERVAL),
    ('Facon', 1.90, 'breakfast',                false,  now() - '4 days'::INTERVAL),
    ('Salami-get-this-straight', 3.00, 'snack', false,  now() - '4 days'::INTERVAL),
    ('Mi-steak', 7.67, 'main',                  false,  now() - '3 days'::INTERVAL),
    ('Ghost Beef', 4.33, 'main',                false,  now() - '3 days'::INTERVAL),
    ('Cheatloaf', 5.00, 'main',                 false,  now() - '3 days'::INTERVAL),
    ('Fried Trickin', 6.40, 'snack',            false,  now() - '3 days'::INTERVAL),
    ('Salmock', 7.16, 'breakfast',              false,  now() - '3 days'::INTERVAL),
    ('Leaf Stroganoff', 6.80, 'main',           false,  now() - '2 days'::INTERVAL),
    ('Chicken Noodle Spoof', 2.50, 'lunch',     false,  now() - '2 days'::INTERVAL),
    ('Pep-parody Pizza', 4.00, 'lunch',         false,  now() - '2 days'::INTERVAL),
    ('Arti-fish-al pie', 8.40, 'main',          false,  now() - '1 days'::INTERVAL),
    ('Bolphony sandwiches', 2.10, 'lunch',      false,  now()),
    ('Chili non-carne', 5.88, 'main',           true,   now()),
    ('Don''t go bacon my heart', 4.20, 'main',  false,  now())
;